apiVersion: v1
kind: Namespace
metadata:
  name: dark
  labels:
    app: dark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dark
  namespace: dark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dark
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: dark
    spec:
      serviceAccountName: dark-operator

      securityContext:
        runAsNonRoot: true

      containers:
      - name: dark
        image: kphoen/dark:latest

        command:
          - /operator
        args:
          - --zap-devel=false

        env:
          - name: GRAFANA_HOST
            value: http://grafana.monitoring.svc.cluster.local
          - name: GRAFANA_TOKEN
            value: 'this should really be in a secret'

        securityContext:
          allowPrivilegeEscalation: false

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 30Mi
            cpu: 5m

      terminationGracePeriodSeconds: 10
