# permissions for end users to edit alertmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertmanager-editor-role
rules:
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers/status
  verbs:
  - get
