# permissions for end users to view alertmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertmanager-viewer-role
rules:
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers/status
  verbs:
  - get
