# permissions for end users to view apikeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apikey-viewer-role
rules:
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys/status
  verbs:
  - get
