# permissions for end users to edit apikeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apikey-editor-role
rules:
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys/status
  verbs:
  - get
