---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - alertmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - apikeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - datasources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - datasources/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - datasources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - grafanadashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - grafanadashboards/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.kevingomez.fr
  resources:
  - grafanadashboards/status
  verbs:
  - get
  - patch
  - update
