apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: grafanadashboards.k8s.kevingomez.fr

spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.kevingomez.fr
  # either Namespaced or Cluster
  scope: Namespaced

  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true

  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: grafanadashboards
    # Used as an alias on the CLI and for display
    singular: grafanadashboard
    # Resource manifests will use this
    kind: GrafanaDashboard
    shortNames:
      - gd
      - grafana-dashboards
      - dashboards
      - dashboard
