name: CI
on: [pull_request]

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1

      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint:v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yaml"
          reporter: github-pr-review
