name: CI
on: [pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ['1.20', '1.21']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=build/golangci.yaml"
          reporter: github-pr-review
          go_version: ${{ matrix.go }}
          cache: false # managed by actions/setup-go

      - name: Tests
        run: make test
        env:
          WITH_COVERAGE: matrix.go == '1.21'

      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          exclude: |
            /vendor/*

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.go == '1.21'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: false

  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: ./docs/
          config_file: build/markdownlint.json

      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          locale: "US"
          exclude: |
            ./vendor/*

      - name: alexjs
        uses: reviewdog/action-alex@v1
        with:
          workdir: ./docs/
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
